/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CosmeticosRouteImport } from './routes/cosmeticos'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as SaturnClubRouteImport } from './routes/saturn-club'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticosRoute = CosmeticosRouteImport.update({
  id: '/cosmeticos',
  path: '/cosmeticos',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const SaturnClubRoute = SaturnClubRouteImport.update({
  id: '/saturn-club',
  path: '/saturn-club',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cosmeticos': typeof CosmeticosRoute
  '/editorial': typeof EditorialRoute
  '/experiencia': typeof ExperienciaRoute
  '/profissionais': typeof ProfissionaisRoute
  '/saturn-club': typeof SaturnClubRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cosmeticos': typeof CosmeticosRoute
  '/editorial': typeof EditorialRoute
  '/experiencia': typeof ExperienciaRoute
  '/profissionais': typeof ProfissionaisRoute
  '/saturn-club': typeof SaturnClubRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cosmeticos': typeof CosmeticosRoute
  '/editorial': typeof EditorialRoute
  '/experiencia': typeof ExperienciaRoute
  '/profissionais': typeof ProfissionaisRoute
  '/saturn-club': typeof SaturnClubRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/cosmeticos'
    | '/editorial'
    | '/experiencia'
    | '/profissionais'
    | '/saturn-club'
    | '/servicos'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/cosmeticos'
    | '/editorial'
    | '/experiencia'
    | '/profissionais'
    | '/saturn-club'
    | '/servicos'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/cosmeticos'
    | '/editorial'
    | '/experiencia'
    | '/profissionais'
    | '/saturn-club'
    | '/servicos'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  CosmeticosRoute: typeof CosmeticosRoute
  EditorialRoute: typeof EditorialRoute
  ExperienciaRoute: typeof ExperienciaRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  SaturnClubRoute: typeof SaturnClubRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmeticos': {
      id: '/cosmeticos'
      path: '/cosmeticos'
      fullPath: '/cosmeticos'
      preLoaderRoute: typeof CosmeticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saturn-club': {
      id: '/saturn-club'
      path: '/saturn-club'
      fullPath: '/saturn-club'
      preLoaderRoute: typeof SaturnClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  CosmeticosRoute: CosmeticosRoute,
  EditorialRoute: EditorialRoute,
  ExperienciaRoute: ExperienciaRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  SaturnClubRoute: SaturnClubRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
